//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoiceapplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvoiceDBEntities : DbContext
    {
        public InvoiceDBEntities()
            : base("name=InvoiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount_details> tblAccount_details { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblInvoice_details> tblInvoice_details { get; set; }
        public virtual DbSet<tblInvoice_payments> tblInvoice_payments { get; set; }
        public virtual DbSet<tblInvoice_products> tblInvoice_products { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    }
}
